### ISSUE TITLE
how to set dragging item class? 

### ISSUE THREAD

**Issue by zhoufanglu** [SortableJS/vue.draggable.next#266]
```html
<draggable
            :animation="200"
            :force-fallback="true"
            drag-class="dragClass"
            ghost-class="ghostClass"
            chosen-class="chosenClass"
            :disabled="true"
            :list="variables.leftList"
            item-key="value"
          >
```
css is useless
```css
/* 1 目标位置占位符的样式 */
.ghostClass {
  background-color: #b0c4de !important;
}
/* 2 选中时样式 */
.chosenClass {
  background-color: #b0c4de !important;
  opacity: 1 !important;
}
/* 3 拖动时样式 */
.dragClass {
  background-color: #b0c4de !important;
  opacity: 1 !important;
  box-shadow: none !important;
  outline: none !important;
  background-image: none !important;
}
```
