### ISSUE TITLE
I'm not sure what went wrong

### ISSUE THREAD

**Issue by hooray** [SortableJS/vue.draggable.next#76]
我不清楚是哪里出了问题，我尝试用这个包，结合 transitions-group 组件去实现类似于 Vue3 官方 [List Move Transitions](https://v3.vuejs.org/guide/transitions-list.html#list-move-transitions) 这样的例子，当移出元素的时候，无法正常添加 v-move 相关的css类。

但我尝试不使用这个包，直接使用 transitions-group 组件，效果是正常的，我没有任何头绪，可能会是什么问题？

Translated

I'm not sure what's wrong, I tried to use this package in combination with the transitions-group component to implement something like the official Vue3 [List Move Transitions](https://v3.vuejs.org/guide/transitions-list.html#list-move-transitions), when moving out elements, the v-move related css classes are not added properly.

But I tried to use the transitions-group component directly without this package and it works fine, I don't have any clue what could be the problem?

**Comment by hooray** [comment]
here is part of the code

```vue
<draggable ref="tab-container" v-model="tabbarList" v-bind="dragOptions" item-key="tabId" draggable=".tab" handle=".drag-handle" tag="transition-group" :component-data="{
	tag: 'div',
	type: 'transition-group',
	name: !isDragging ? 'tabbar' : null
}" class="tab-container" :class="{'dragging': isDragging}" @start="isDragging = true" @end="isDragging = false"
>
	<template #item="{element}">
		<div :key="element.tabId" :ref="`tab-${element.tabId}`" class="tab">
			...
		</div>
	</template>
</draggable>
```

```scss
    .tabbar-enter-from,
    .tabbar-leave-to {
        opacity: 0;
        transform: translateY(30px);
    }
    &.tabs-ontop {
        .tabbar-enter-from,
        .tabbar-leave-to {
            opacity: 0;
            transform: translateY(-30px);
        }
    }
    .tabbar-enter-active {
        transition: all 0.2s;
    }
    .tabbar-leave-active {
        position: absolute !important;
        transition: all 0.2s;
    }
    .tabbar-move {
        transition: transform 0.2s;
    }
```
